spring:
  application:
    name: consumer
server:
  port: 90
eureka:
  client:
    service-url:
#      defaultZone: http://registrar:7900/eureka/   #  docker环境用这个配置
      defaultZone: http://lisz:666@localhost:7900/eureka/
    healthcheck:
      enabled: true
  instance:
    metadata-map:
      dalao: lisz-hahaha
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true